sonar.projectKey=mobile-credential-sharing-ios-oid4vp
sonar.projectName=mobile-credential-sharing-ios-oid4vp
sonar.organization=govuk-one-login

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.
sonar.tests=,

sonar.test.inclusions=**/*Tests/**/*Tests
sonar.exclusions=**/Tests/**,Tests/**,**/*Tests/**,**/*Tests,UITests/**,**/*Preview*,Package.swift,**/Package.swift

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
sonar.pullrequest.provider=github
sonar.pullrequest.github.repository=govuk-one-login/mobile-credential-sharing-ios