sonar.projectKey=mobile-credential-sharing-ios-oid4vp
sonar.projectName=mobile-credential-sharing-ios-oid4vp
sonar.organization=govuk-one-login

# Paths are relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=\
  SharingBluetoothTransport/Sources,\
  SharingCameraService/Sources,\
  SharingPrerequisiteGate/Sources,\
  SharingCryptoService/Sources,\
  SharingOrchestration/Sources,\
  SharingValidationService/Sources,\
  CredentialSharingUI/Sources,\
  mobile-credential-sharing-ios/mobile-credential-sharing-ios

sonar.tests=\
  SharingBluetoothTransport/Tests,\
  SharingCameraService/Tests,\
  SharingPrerequisiteGate/Tests,\
  SharingCryptoService/Tests,\
  SharingOrchestration/Tests,\
  SharingValidationService/Tests,\
  CredentialSharingUI/Tests,\
  ISO18013-6Tests,\
  mobile-credential-sharing-ios/mobile-credential-sharing-iosTests,\
  mobile-credential-sharing-ios/mobile-credential-sharing-iosUITests

# Keep generated/manifest files, assets and previews out of main-code analysis.
sonar.exclusions=**/*Preview*,**/Package.swift,**/Assets.xcassets/**,**/*.png,**/*.storyboard,**/*.txt,**/SceneDelegate.swift

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
sonar.pullrequest.provider=github
sonar.pullrequest.github.repository=govuk-one-login/mobile-credential-sharing-ios