name: iOS Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: macos-26
    permissions:
      contents: write
    steps:
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_26.4.1.app

      - name: Add path globally
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@v6
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Increment Version and Create Release
        id: versioning
        uses: Oliver-Binns/Versioning@34801d858f89c7147ef277c73645bd23da9db9b7 # pin@v1.4.5
        with:
          ACTION_TYPE: 'Release'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to App Store Connect - Build
        env:
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8
          CONFIGURATION: Build
          AWS_SECRET_SIGNING_KEY_PASSWORD_ENCODED: ${{ secrets.AWS_SECRET_SIGNING_KEY_PASSWORD_ENCODED }}
          AWS_SECRET_DISTRIBUTION_P12_ENCODED: ${{ secrets.AWS_SECRET_DISTRIBUTION_P12_ENCODED }}
          AWS_SECRET_AUTH_KEY_P8_ENCODED: ${{ secrets.AWS_SECRET_AUTH_KEY_P8_ENCODED }}
        run: |-
          git_branch="${GITHUB_REF_NAME}"
          echo "Pushed to branch: $git_branch"

          bundle install

          # create variables
          CERTIFICATE_PATH="$RUNNER_TEMP/distribution.p12"
          APIKEY_PATH="$RUNNER_TEMP/apikey.p8"

          # import certificates from secrets
          echo -n "$AWS_SECRET_DISTRIBUTION_P12_ENCODED" | base64 --decode -o "$CERTIFICATE_PATH"
          echo -n "$AWS_SECRET_AUTH_KEY_P8_ENCODED} | base64 --decode -o "$APIKEY_PATH"

          bundle exec fastlane prerelease \
            certificate_path:$CERTIFICATE_PATH \
            certificate_password:$AWS_SECRET_SIGNING_KEY_PASSWORD_ENCODED \
            apikey_path:$APIKEY_PATH
