name: iOS Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate_lint:
    name: Validate & Lint
    runs-on: macos-26
    timeout-minutes: 2
    steps:
      - name: Validate Pull Request Name
        id: versioning
        uses: Oliver-Binns/Versioning@34801d858f89c7147ef277c73645bd23da9db9b7 # pin@v1.4.5
        with:
          ACTION_TYPE: 'Validate'

      - name: Add Path Globally
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@v6
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Run Linter
        run: |
          brew install swiftlint
          swiftlint --strict

  build:
    needs: [validate_lint]
    name: Build & Test
    if: github.event.pull_request.draft == false
    runs-on: macos-26
    timeout-minutes: 28

    steps:
      - name: Add path globally
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@v6
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Build
        env:
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          WORKSPACE: ${{ github.workspace }}
          SOURCE_BRANCH: ${{ github.head_ref }}
          TARGET_BRANCH: ${{ github.base_ref }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

          brew install sonar-scanner
          bundle install

          bundle exec fastlane test scheme:"Sharing-Demo" \
            sonar_token:$SONAR_TOKEN \
            workspace:$WORKSPACE \
            source_branch:$SOURCE_BRANCH \
            target_branch:$TARGET_BRANCH \
            testplan:"UnitTestPlan" \
            pr_number:$PR_NUMBER

      # Check the Quality Gate status.
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b # pin@v1.2.0
        # Force to fail step after specific time.
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
