name: iOS Quality Report

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-26
    permissions:
      contents: write

    steps:
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_26.4.1.app

      - name: Add path globally
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@v6
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Run Linter
        run: |
          brew install swiftlint
          swiftlint lint --strict --config .swiftlint.yml

      - name: Build
        env:
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          WORKSPACE: ${{ github.workspace }}
        run: |
          brew install sonar-scanner
          bundle install

          bundle exec fastlane test \
            scheme:"Sharing-Demo" \
            sonar_token:$SONAR_TOKEN \
            workspace:$WORKSPACE
